### ISSUE TITLE
Remove hackforums

### ISSUE THREAD

**Issue by duraki** [vitalysim/Awesome-Hacking-Resources#111] opened 2019-04-21 16:36 UTC
LOL srsly?

**Comment by dukeofdisaster** [comment] 2019-04-29 22:39
The entire point of this repo is to curate resources where people can learn, with lean towards free resources; while I assume that you're raising the issue because you disapprove of hackforums shady side, the fact remains that it's a free resource. @vitalysim I vote for closing this issue without removal.

**Comment by vitalysim** [comment] 2019-05-01 17:44
@dukeofdisaster  I agree with you.

The issue is closed!

**Closed by vitalysim** 2019-05-01 17:44 UTC
